apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "helm-bitwarden-unified.fullname" . }}-certificate
spec:
  commonName: {{ .Values.environment.BW_DOMAIN }}
  secretName: bitwarden-certificate
  dnsNames:
    - {{ .Values.environment.BW_DOMAIN }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer