apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-bitwarden-unified.fullname" . }}-environment
data:
{{- range $key, $val := .Values.environment }}
  {{ $key }}: "{{ $val }}"
{{- end }}
