apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm-bitwarden-unified.fullname" . }}-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi